

info:
  description: myfeed discover server based on spring-cloud-netflix-eureka-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0

server:
  port: 11010