info:
  description: myfeed feed service

server:
  port: 11060

spring:
  cloud:
    stream:
      bindings:
        userinitialized:
          destination: userinit
          content-type: application/x-java-object;type=myfeed.feed.User
          group: feeduserinit

logging:
  level:
    com.netflix.hystrix: DEBUG