info:
  description: myfeed router based on spring-cloud-netflix-zuul

server:
  port: 11080

management:
  port: 11081
  security:
    enabled: false

security:
  user:
    password: user
  #TODO: router needs to know about these?
  ignored: /admin/**,/favicon.ico,/index.html,/profile.html,/feed.html,/js/**,/css/**,/webjars/**
  sessions: IF_REQUIRED

eureka:
  client:
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10

ribbon:
  ServerListRefreshInterval: 5000

spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/profile
      loginPath: /profile/login
      logoutPath: /profile/logout
    client:
      clientId: a819b31a2358aa755df9
      clientSecret: 2cf02e22439bfd8b7396c19567de4587dd39d4d8
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false