info:
  description: myfeed ui server

server:
  port: 11040

security:
#  user:
#    password: user
  ignored: /,/favicon.ico,/dashboard.html,/index.html,/home.html,/js/**,/css/**,/webjars/**

spring:
  oauth2:
    resource:
      userInfoUri: https://api.github.com/user
      id: github
