info:
  description: myfeed ui server

server:
  port: 11040

management:
  port: 11041
  security:
    enabled: false

myfeed:
  ui:
    login-redirect: http://www.myfeed.com:11080

security:
#  user:
#    password: user
  ignored: /,/favicon.ico,/dashboard.html,/index.html,/feed.html,/js/**,/css/**,/webjars/**

spring:
  oauth2:
    resource:
      userInfoUri: https://api.github.com/user
      id: github
