spring:
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: git@github.com:spencergibb/myfeed-config.git
        health:
          repositories:
            myfeed-ui:
              profiles: default
            myfeed-ui-dev:
              name: myfeed-ui
              profiles: development

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery.myfeed.com:11010/eureka/

server:
  port: 11020
